package codegen

import (
	"fmt"
	"strconv"
	"strings"

	"peddle/ast"
)

type Generator struct {
	out strings.Builder

	functions map[string]*ast.FunctionDecl
	frames    map[string]*Frame

	currentFn    *ast.FunctionDecl
	currentFrame *Frame

	literals []string

	usedPrint bool
	usedTmp16 bool

	labelCounter int
}

type Frame struct {
	FunctionName string
	Symbols      map[string]Symbol
	Return       *Symbol
}

type Symbol struct {
	SourceName string
	Label      string
	Type       ast.Type
	Size       int
}

func New() *Generator {
	return &Generator{
		functions: map[string]*ast.FunctionDecl{},
		frames:    map[string]*Frame{},
	}
}

func (g *Generator) Generate(p *ast.Program) (string, error) {
	for _, fn := range p.Functions {
		g.functions[fn.Name] = fn
		g.frames[fn.Name] = g.buildFrame(fn)
	}

	g.emitHeader()

	for _, fn := range p.Functions {
		if err := g.genFunction(fn); err != nil {
			return "", err
		}
	}

	g.emitRuntime()
	g.emitLiterals()
	g.emitStaticData()

	return g.out.String(), nil
}

func (g *Generator) buildFrame(fn *ast.FunctionDecl) *Frame {
	frame := &Frame{
		FunctionName: fn.Name,
		Symbols:      map[string]Symbol{},
	}

	for _, p := range fn.Params {
		frame.Symbols[p.Name] = Symbol{
			SourceName: p.Name,
			Label:      fn.Name + "_" + p.Name,
			Type:       p.Type,
			Size:       sizeof(p.Type),
		}
	}

	for _, l := range fn.Locals {
		frame.Symbols[l.Name] = Symbol{
			SourceName: l.Name,
			Label:      fn.Name + "_" + l.Name,
			Type:       l.Type,
			Size:       sizeof(l.Type),
		}
	}

	if fn.ReturnType.Name != "" {
		frame.Return = &Symbol{
			SourceName: "return",
			Label:      fn.Name + "_return",
			Type:       fn.ReturnType,
			Size:       sizeof(fn.ReturnType),
		}
	}

	return frame
}

func (g *Generator) emitHeader() {
	g.emit(`; generated by peddlec

ZP_TMP0     = $fb
ZP_TMP1     = $fc
ZP_PTR0_LO  = $fd
ZP_PTR0_HI  = $fe

* = $0801
.word basic_next
.word 10
.byte $9e
.text "2064"
.byte 0

basic_next:
.word 0

* = $0810

start:
    jsr main
    rts
`)
}

func (g *Generator) genFunction(fn *ast.FunctionDecl) error {
	g.currentFn = fn
	g.currentFrame = g.frames[fn.Name]

	g.emit(fn.Name + ":")

	for _, stmt := range fn.Body {
		if err := g.genStmt(stmt); err != nil {
			return err
		}
	}

	g.emit("    rts")
	g.emit("")
	return nil
}

func (g *Generator) genStmt(s ast.Stmt) error {
	switch stmt := s.(type) {
	case *ast.AssignStmt:
		return g.genAssign(stmt)

	case *ast.CallStmt:
		return g.genCallStmt(stmt)

	case *ast.WhileStmt:
		return g.genWhile(stmt)

	case *ast.IfStmt:
		return g.genIf(stmt)

	case *ast.ReturnStmt:
		return g.genReturn(stmt)

	default:
		return fmt.Errorf("unsupported statement")
	}
}

func (g *Generator) genAssign(a *ast.AssignStmt) error {
	switch target := a.Target.(type) {
	case *ast.VarLValue:
		sym, ok := g.resolve(target.Name)
		if !ok {
			return fmt.Errorf("unknown variable %q", target.Name)
		}

		if err := g.genExprTo(a.Value, sym.Type); err != nil {
			return err
		}

		g.storeAIntoSymbol(sym)
		return nil

	case *ast.IndexLValue:
		arraySym, ok := g.resolve(target.Name)
		if !ok {
			return fmt.Errorf("unknown array %q", target.Name)
		}
		if !arraySym.Type.IsArray {
			return fmt.Errorf("%q is not an array", target.Name)
		}

		elemType := ast.Type{Name: arraySym.Type.Name}

		if elemType.Name == "int" {
			return fmt.Errorf("int array assignment is not implemented yet")
		}

		if err := g.genExprTo(a.Value, elemType); err != nil {
			return err
		}
		g.emit("    sta ZP_TMP0")

		if err := g.genArrayIndexToY(arraySym, target.Index); err != nil {
			return err
		}

		g.emit("    lda ZP_TMP0")
		g.emit("    sta (ZP_PTR0_LO), y")
		return nil

	default:
		return fmt.Errorf("unsupported assignment target")
	}
}

func (g *Generator) genCallStmt(c *ast.CallStmt) error {
	_, err := g.genCall(c.Name, c.Args)
	return err
}

func (g *Generator) genWhile(w *ast.WhileStmt) error {
	start := g.newLabel()
	end := g.newLabel()

	g.emit(start + ":")

	if err := g.genConditionFalseJump(w.Cond, end); err != nil {
		return err
	}

	for _, stmt := range w.Body {
		if err := g.genStmt(stmt); err != nil {
			return err
		}
	}

	g.emit(fmt.Sprintf("    jmp %s", start))
	g.emit(end + ":")
	return nil
}

func (g *Generator) genIf(i *ast.IfStmt) error {
	elseLabel := g.newLabel()
	endLabel := g.newLabel()

	if err := g.genConditionFalseJump(i.Cond, elseLabel); err != nil {
		return err
	}

	for _, stmt := range i.Then {
		if err := g.genStmt(stmt); err != nil {
			return err
		}
	}

	g.emit(fmt.Sprintf("    jmp %s", endLabel))
	g.emit(elseLabel + ":")

	for _, stmt := range i.Else {
		if err := g.genStmt(stmt); err != nil {
			return err
		}
	}

	g.emit(endLabel + ":")
	return nil
}

func (g *Generator) genReturn(r *ast.ReturnStmt) error {
	if g.currentFrame.Return == nil {
		g.emit("    rts")
		return nil
	}

	if r.Value == nil {
		return fmt.Errorf("missing return value")
	}

	if err := g.genExprTo(r.Value, g.currentFrame.Return.Type); err != nil {
		return err
	}

	g.storeAIntoSymbol(*g.currentFrame.Return)
	g.emit("    rts")
	return nil
}

func (g *Generator) genExprTo(e ast.Expr, target ast.Type) error {
	switch expr := e.(type) {
	case *ast.NumberExpr:
		n, err := strconv.Atoi(expr.Value)
		if err != nil {
			return err
		}

		if target.Name == "int" {
			g.emit(fmt.Sprintf("    lda #<%d", n))
			g.emit("    sta ZP_TMP0")
			g.emit(fmt.Sprintf("    lda #>%d", n))
			g.emit("    sta ZP_TMP1")
			g.usedTmp16 = true
			return nil
		}

		g.emit(fmt.Sprintf("    lda #%d", n&0xff))
		return nil

	case *ast.IdentExpr:
		sym, ok := g.resolve(expr.Name)
		if !ok {
			return fmt.Errorf("unknown variable %q", expr.Name)
		}

		g.loadSymbol(sym)
		return nil

	case *ast.IndexExpr:
		arraySym, ok := g.resolve(expr.Name)
		if !ok {
			return fmt.Errorf("unknown array %q", expr.Name)
		}
		if !arraySym.Type.IsArray {
			return fmt.Errorf("%q is not an array", expr.Name)
		}

		if arraySym.Type.Name == "int" {
			return fmt.Errorf("int array reads are not implemented yet")
		}

		if err := g.genArrayIndexToY(arraySym, expr.Index); err != nil {
			return err
		}

		g.emit("    lda (ZP_PTR0_LO), y")
		return nil

	case *ast.BinaryExpr:
		return g.genBinaryTo(expr, target)

	case *ast.CallExpr:
		retType, err := g.genCall(expr.Name, expr.Args)
		if err != nil {
			return err
		}

		if retType.Name == "" {
			return fmt.Errorf("function %s does not return a value", expr.Name)
		}

		fnFrame := g.frames[expr.Name]
		if fnFrame == nil || fnFrame.Return == nil {
			return fmt.Errorf("missing return slot for %s", expr.Name)
		}

		g.loadSymbol(*fnFrame.Return)
		return nil

	case *ast.StringExpr:
		return fmt.Errorf("string expression cannot be used here directly")

	default:
		return fmt.Errorf("unsupported expression")
	}
}

func (g *Generator) genBinaryTo(b *ast.BinaryExpr, target ast.Type) error {
	switch b.Op {
	case "+", "-":
		if target.Name == "int" {
			return g.genBinaryInt(b)
		}
		return g.genBinaryByte(b)

	case "==", "!=", "<", "<=", ">", ">=":
		return g.genComparisonToBool(b)

	default:
		return fmt.Errorf("unsupported binary op %q", b.Op)
	}
}

func (g *Generator) genBinaryByte(b *ast.BinaryExpr) error {
	if err := g.genExprTo(b.Right, ast.Type{Name: "byte"}); err != nil {
		return err
	}
	g.emit("    sta ZP_TMP0")

	if err := g.genExprTo(b.Left, ast.Type{Name: "byte"}); err != nil {
		return err
	}

	switch b.Op {
	case "+":
		g.emit("    clc")
		g.emit("    adc ZP_TMP0")
	case "-":
		g.emit("    sec")
		g.emit("    sbc ZP_TMP0")
	}

	return nil
}

func (g *Generator) genBinaryInt(b *ast.BinaryExpr) error {
	if err := g.genExprTo(b.Right, ast.Type{Name: "int"}); err != nil {
		return err
	}
	g.emit("    lda ZP_TMP0")
	g.emit("    sta peddle_tmp_int0")
	g.emit("    lda ZP_TMP1")
	g.emit("    sta peddle_tmp_int0+1")

	if err := g.genExprTo(b.Left, ast.Type{Name: "int"}); err != nil {
		return err
	}

	switch b.Op {
	case "+":
		g.emit("    clc")
		g.emit("    lda ZP_TMP0")
		g.emit("    adc peddle_tmp_int0")
		g.emit("    sta ZP_TMP0")
		g.emit("    lda ZP_TMP1")
		g.emit("    adc peddle_tmp_int0+1")
		g.emit("    sta ZP_TMP1")
	case "-":
		g.emit("    sec")
		g.emit("    lda ZP_TMP0")
		g.emit("    sbc peddle_tmp_int0")
		g.emit("    sta ZP_TMP0")
		g.emit("    lda ZP_TMP1")
		g.emit("    sbc peddle_tmp_int0+1")
		g.emit("    sta ZP_TMP1")
	}

	g.usedTmp16 = true
	return nil
}

func (g *Generator) genComparisonToBool(b *ast.BinaryExpr) error {
	if err := g.genExprTo(b.Right, ast.Type{Name: "byte"}); err != nil {
		return err
	}
	g.emit("    sta ZP_TMP0")

	if err := g.genExprTo(b.Left, ast.Type{Name: "byte"}); err != nil {
		return err
	}

	trueLabel := g.newLabel()
	endLabel := g.newLabel()

	g.emit("    cmp ZP_TMP0")

	switch b.Op {
	case "==":
		g.emit(fmt.Sprintf("    beq %s", trueLabel))
	case "!=":
		g.emit(fmt.Sprintf("    bne %s", trueLabel))
	case "<":
		g.emit(fmt.Sprintf("    bcc %s", trueLabel))
	case "<=":
		g.emit(fmt.Sprintf("    bcc %s", trueLabel))
		g.emit(fmt.Sprintf("    beq %s", trueLabel))
	case ">":
		g.emit(fmt.Sprintf("    beq %s", endLabel))
		g.emit(fmt.Sprintf("    bcs %s", trueLabel))
	case ">=":
		g.emit(fmt.Sprintf("    bcs %s", trueLabel))
	default:
		return fmt.Errorf("unsupported comparison operator %q", b.Op)
	}

	g.emit("    lda #0")
	g.emit(fmt.Sprintf("    jmp %s", endLabel))
	g.emit(trueLabel + ":")
	g.emit("    lda #1")
	g.emit(endLabel + ":")

	return nil
}

func (g *Generator) genConditionFalseJump(cond ast.Expr, falseLabel string) error {
	b, ok := cond.(*ast.BinaryExpr)
	if !ok {
		if err := g.genExprTo(cond, ast.Type{Name: "byte"}); err != nil {
			return err
		}
		g.emit("    cmp #0")
		g.emit(fmt.Sprintf("    beq %s", falseLabel))
		return nil
	}

	if err := g.genExprTo(b.Right, ast.Type{Name: "byte"}); err != nil {
		return err
	}
	g.emit("    sta ZP_TMP0")

	if err := g.genExprTo(b.Left, ast.Type{Name: "byte"}); err != nil {
		return err
	}

	g.emit("    cmp ZP_TMP0")

	switch b.Op {
	case "==":
		g.emit(fmt.Sprintf("    bne %s", falseLabel))
	case "!=":
		g.emit(fmt.Sprintf("    beq %s", falseLabel))
	case "<":
		g.emit(fmt.Sprintf("    bcs %s", falseLabel))
	case ">=":
		g.emit(fmt.Sprintf("    bcc %s", falseLabel))
	case "<=":
		after := g.newLabel()
		g.emit(fmt.Sprintf("    bcc %s", after))
		g.emit(fmt.Sprintf("    beq %s", after))
		g.emit(fmt.Sprintf("    jmp %s", falseLabel))
		g.emit(after + ":")
	case ">":
		g.emit(fmt.Sprintf("    beq %s", falseLabel))
		g.emit(fmt.Sprintf("    bcc %s", falseLabel))
	default:
		return fmt.Errorf("unsupported condition operator %q", b.Op)
	}

	return nil
}

func (g *Generator) genCall(name string, args []ast.Expr) (ast.Type, error) {
	switch name {
	case "print":
		if len(args) != 1 {
			return ast.Type{}, fmt.Errorf("print expects one argument")
		}
		g.usedPrint = true

		switch arg := args[0].(type) {
		case *ast.StringExpr:
			label := g.addLiteral(arg.Value)
			g.emit(fmt.Sprintf("    lda #<%s", label))
			g.emit("    sta ZP_PTR0_LO")
			g.emit(fmt.Sprintf("    lda #>%s", label))
			g.emit("    sta ZP_PTR0_HI")
			g.emit("    jsr peddle_print_string")
			return ast.Type{}, nil

		case *ast.IdentExpr:
			sym, ok := g.resolve(arg.Name)
			if !ok {
				return ast.Type{}, fmt.Errorf("unknown variable %q", arg.Name)
			}
			g.emit(fmt.Sprintf("    lda #<%s", sym.Label))
			g.emit("    sta ZP_PTR0_LO")
			g.emit(fmt.Sprintf("    lda #>%s", sym.Label))
			g.emit("    sta ZP_PTR0_HI")
			g.emit("    jsr peddle_print_string")
			return ast.Type{}, nil

		default:
			return ast.Type{}, fmt.Errorf("unsupported print argument")
		}

	case "poke":
		if len(args) != 2 {
			return ast.Type{}, fmt.Errorf("poke expects two arguments")
		}

		addrNum, ok := args[0].(*ast.NumberExpr)
		if !ok {
			return ast.Type{}, fmt.Errorf("poke currently requires constant address")
		}

		value := args[1]
		if err := g.genExprTo(value, ast.Type{Name: "byte"}); err != nil {
			return ast.Type{}, err
		}

		addr, err := strconv.Atoi(addrNum.Value)
		if err != nil {
			return ast.Type{}, err
		}

		g.emit(fmt.Sprintf("    sta $%04x", addr))
		return ast.Type{}, nil
	}

	fn, ok := g.functions[name]
	if !ok {
		return ast.Type{}, fmt.Errorf("unknown function %q", name)
	}

	frame := g.frames[name]

	for i, arg := range args {
		param := fn.Params[i]
		sym := frame.Symbols[param.Name]

		if err := g.genExprTo(arg, param.Type); err != nil {
			return ast.Type{}, err
		}

		g.storeAIntoSymbol(sym)
	}

	g.emit(fmt.Sprintf("    jsr %s", name))
	return fn.ReturnType, nil
}

func (g *Generator) genArrayIndexToY(arraySym Symbol, index ast.Expr) error {
	g.emit(fmt.Sprintf("    lda #<%s", arraySym.Label))
	g.emit("    sta ZP_PTR0_LO")
	g.emit(fmt.Sprintf("    lda #>%s", arraySym.Label))
	g.emit("    sta ZP_PTR0_HI")

	if err := g.genExprTo(index, ast.Type{Name: "byte"}); err != nil {
		return err
	}

	if arraySym.Type.Name == "int" {
		g.emit("    asl")
	}

	g.emit("    tay")
	return nil
}

func (g *Generator) loadSymbol(sym Symbol) {
	if sym.Type.Name == "int" && !sym.Type.IsArray {
		g.emit(fmt.Sprintf("    lda %s", sym.Label))
		g.emit("    sta ZP_TMP0")
		g.emit(fmt.Sprintf("    lda %s+1", sym.Label))
		g.emit("    sta ZP_TMP1")
		g.usedTmp16 = true
		return
	}

	g.emit(fmt.Sprintf("    lda %s", sym.Label))
}

func (g *Generator) storeAIntoSymbol(sym Symbol) {
	if sym.Type.Name == "int" && !sym.Type.IsArray {
		g.emit("    lda ZP_TMP0")
		g.emit(fmt.Sprintf("    sta %s", sym.Label))
		g.emit("    lda ZP_TMP1")
		g.emit(fmt.Sprintf("    sta %s+1", sym.Label))
		g.usedTmp16 = true
		return
	}

	g.emit(fmt.Sprintf("    sta %s", sym.Label))
}

func (g *Generator) resolve(name string) (Symbol, bool) {
	if g.currentFrame == nil {
		return Symbol{}, false
	}
	sym, ok := g.currentFrame.Symbols[name]
	return sym, ok
}

func (g *Generator) addLiteral(value string) string {
	label := fmt.Sprintf("literal_%d", len(g.literals))
	g.literals = append(g.literals, value)
	return label
}

func (g *Generator) newLabel() string {
	g.labelCounter++
	return fmt.Sprintf("L%d", g.labelCounter)
}

func (g *Generator) emitRuntime() {
	g.emit("")
	g.emit("; runtime")

	if g.usedTmp16 {
		g.emit("peddle_tmp_int0:")
		g.emit("    .fill 2, 0")
	}

	if g.usedPrint {
		g.emit(`
peddle_print_string:
    ldy #0

peddle_print_string_loop:
    lda (ZP_PTR0_LO), y
    beq peddle_print_string_done

    jsr $ffd2

    iny
    bne peddle_print_string_loop

    inc ZP_PTR0_HI
    jmp peddle_print_string_loop

peddle_print_string_done:
    rts
`)
	}
}

func (g *Generator) emitLiterals() {
	if len(g.literals) == 0 {
		return
	}

	g.emit("")
	g.emit("; literals")

	for i, lit := range g.literals {
		g.emit(fmt.Sprintf("literal_%d:", i))
		g.emit(fmt.Sprintf("    .byte %s,0", asmStringBytes(lit)))
	}
}

func (g *Generator) emitStaticData() {
	g.emit("")
	g.emit("; static data")

	for _, frame := range g.frames {
		for _, sym := range frame.Symbols {
			g.emit(fmt.Sprintf("%s:", sym.Label))
			g.emit(fmt.Sprintf("    .fill %d, 0", sym.Size))
		}

		if frame.Return != nil {
			g.emit(fmt.Sprintf("%s:", frame.Return.Label))
			g.emit(fmt.Sprintf("    .fill %d, 0", frame.Return.Size))
		}
	}
}

func (g *Generator) emit(s string) {
	g.out.WriteString(s)
	g.out.WriteString("\n")
}

func sizeof(t ast.Type) int {
	base := 0

	switch t.Name {
	case "byte", "char", "bool":
		base = 1
	case "int":
		base = 2
	default:
		base = 1
	}

	if t.IsArray {
		return base * t.ArrayLen
	}

	return base
}

func asmStringBytes(s string) string {
	var parts []string

	for _, r := range s {
		switch r {
		case '\n':
			parts = append(parts, "13")
		case '"':
			parts = append(parts, "34")
		default:
			parts = append(parts, strconv.Quote(string(r)))
		}
	}

	return strings.Join(parts, ",")
}
