package codegen

import "fmt"

func (g *Generator) emitHeader() {
	g.emit(`; generated by peddlec

ZP_TMP0     = $fb
ZP_TMP1     = $fc
ZP_PTR0_LO  = $fd
ZP_PTR0_HI  = $fe

* = $0801
.word basic_next
.word 10
.byte $9e
.text "2064"
.byte 0

basic_next:
.word 0

* = $0810

start:
    jsr main
    rts
`)
}

func (g *Generator) emitRuntime() {
	g.emit("")
	g.emit("; runtime")

	if g.usedTmp16 {
		g.emit("peddle_tmp_int0:")
		g.emit("    .fill 2, 0")
	}

	if g.usedPrint {
		g.emit(`
peddle_print_string:
    ldy #0

peddle_print_string_loop:
    lda (ZP_PTR0_LO), y
    beq peddle_print_string_done

    jsr $ffd2

    iny
    bne peddle_print_string_loop

    inc ZP_PTR0_HI
    jmp peddle_print_string_loop

peddle_print_string_done:
    rts
`)
	}
}

func (g *Generator) emitLiterals() {
	if len(g.literals) == 0 {
		return
	}

	g.emit("")
	g.emit("; literals")

	for i, lit := range g.literals {
		g.emit(fmt.Sprintf("literal_%d:", i))
		g.emit(fmt.Sprintf("    .byte %s,0", asmStringBytes(lit)))
	}
}

func (g *Generator) emitStaticData() {
	g.emit("")
	g.emit("; static data")

	for _, frame := range g.frames {
		for _, sym := range frame.Symbols {
			g.emit(fmt.Sprintf("%s:", sym.Label))
			g.emit(fmt.Sprintf("    .fill %d, 0", sym.Size))
		}

		if frame.Return != nil {
			g.emit(fmt.Sprintf("%s:", frame.Return.Label))
			g.emit(fmt.Sprintf("    .fill %d, 0", frame.Return.Size))
		}
	}
}

func (g *Generator) emit(s string) {
	g.out.WriteString(s)
	g.out.WriteString("\n")
}
