package codegen

import (
	"fmt"

	"peddle/ast"
)

func (g *Generator) emitHeader() {
	g.emit(`; generated by peddlec

ZP_TMP0     = $fb
ZP_TMP1     = $fc
ZP_PTR0_LO  = $fd
ZP_PTR0_HI  = $fe

* = $0801
.word basic_next
.word 10
.byte $9e
.text "2064"
.byte 0

basic_next:
.word 0

* = $0810

start:
    jsr main
    rts
`)
}

func (g *Generator) emitRuntime() {
	g.emit("")
	g.emit("; runtime")

	if g.usedTmp16 || g.usedPrint {
		g.emit("peddle_tmp_int0:")
		g.emit("    .fill 2, 0")
	}

	if g.usedPrint {
		g.emit(`
peddle_print_string:
    ldy #0

peddle_print_string_loop:
    lda (ZP_PTR0_LO), y
    beq peddle_print_string_done

    jsr $ffd2

    iny
    bne peddle_print_string_loop

    inc ZP_PTR0_HI
    jmp peddle_print_string_loop

peddle_print_string_done:
    rts

peddle_print_counted_string:
    lda peddle_tmp_int0
    ora peddle_tmp_int0+1
    beq peddle_print_counted_string_done

    ldy #0
    lda (ZP_PTR0_LO), y
    jsr $ffd2

    inc ZP_PTR0_LO
    bne peddle_print_counted_string_no_carry
    inc ZP_PTR0_HI

peddle_print_counted_string_no_carry:
    lda peddle_tmp_int0
    bne peddle_print_counted_string_dec_low
    dec peddle_tmp_int0+1

peddle_print_counted_string_dec_low:
    dec peddle_tmp_int0
    jmp peddle_print_counted_string

peddle_print_counted_string_done:
    rts
`)
	}
}

func (g *Generator) emitLiterals() {
	if len(g.literals) == 0 {
		return
	}

	g.emit("")
	g.emit("; literals")

	for i, lit := range g.literals {
		g.emit(fmt.Sprintf("literal_%d:", i))
		g.emit(fmt.Sprintf("    .byte %s,0", asmStringBytes(lit)))
	}
}

func (g *Generator) emitStaticData() {
	g.emit("")
	g.emit("; static data")

	for _, frame := range g.frames {
		for _, sym := range frame.Symbols {
			g.emit(fmt.Sprintf("%s:", sym.Label))
			g.emitStaticValue(sym.Type)
		}

		if frame.Return != nil {
			g.emit(fmt.Sprintf("%s:", frame.Return.Label))
			g.emitStaticValue(frame.Return.Type)
		}
	}
}

func (g *Generator) emitStaticValue(t ast.Type) {
	if t.IsArray {
		initialLen := t.ArrayLen
		if t.Name == "char" {
			initialLen = 0
		}

		g.emit(fmt.Sprintf("    .word %d", t.ArrayLen))
		g.emit(fmt.Sprintf("    .word %d", initialLen))

		elemType := ast.Type{Name: t.Name}

		if _, ok := g.structs[t.Name]; ok {
			for i := 0; i < t.ArrayLen; i++ {
				g.emitStaticValue(elemType)
			}
			return
		}

		g.emit(fmt.Sprintf("    .fill %d, 0", g.sizeof(elemType)*t.ArrayLen))
		return
	}

	if s, ok := g.structs[t.Name]; ok {
		for _, f := range s.Fields {
			g.emitStaticValue(f.Type)
		}
		return
	}

	g.emit(fmt.Sprintf("    .fill %d, 0", g.sizeof(t)))
}

func (g *Generator) emit(s string) {
	g.out.WriteString(s)
	g.out.WriteString("\n")
}
