#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LANGUAGE_DIR="$ROOT_DIR/docs/language"
OUT_FILE="$ROOT_DIR/docs/peddle_complete_language_guide.md"

{
    printf '<!-- Generated by scripts/build_complete_language_guide.sh. Do not edit directly. -->\n\n'

    first=1
    for file in "$LANGUAGE_DIR"/README.md "$LANGUAGE_DIR"/[0-9][0-9]-*.md; do
        if [[ ! -f "$file" ]]; then
            continue
        fi

        if [[ "$first" -eq 0 ]]; then
            printf '\n---\n\n'
        fi

        cat "$file"
        first=0
    done
} > "$OUT_FILE"

printf 'wrote %s\n' "$OUT_FILE"
